### PR TITLE
Cringedev

### PR DESCRIPTION
**Pull request by TheodorePtr**
PR to `main` for the first release

### CODE REVIEW

**Comment by TheodorePtr** [comment]
Hold out team, diagrams are needed

**Comment by TheodorePtr** [comment]
> Hold out team, diagrams are needed

We can add them to project wiki

**Comment by popuskowski** [comment]
Great job, I am literally about to cry. Out of joy of creation, of course.

**Comment by littlephony** [comment]
My honest reaction 💪💪💪

**Comment by popuskowski** [comment]
Literally me

**Pull request merged**
